AWSTemplateFormatVersion: '2010-09-09'
Transform: AWS::Serverless-2016-10-31
Description: >
  image-gen

Globals:
  Function:
    Timeout: 30
  Api:
    TracingEnabled: true
    EndpointConfiguration: REGIONAL

Resources:
  HelloWorldFunction:
    Type: AWS::Serverless::Function
    Properties:
      CodeUri: hello_world/
      Handler: app.lambda_handler
      Runtime: python3.9
      Architectures:
        - x86_64
      Environment:
        Variables:
          BUCKET_NAME: "pgr301-couch-explorers"
      Policies:
        - Statement:
            Effect: Allow
            Action: "bedrock:InvokeModel"
            Resource: "arn:aws:bedrock:us-east-1::foundation-model/amazon.titan-image-generator-v1"
        - Statement:
            Effect: Allow
            Action: "s3:PutObject"
            Resource: "arn:aws:s3:::pgr301-couch-explorers/*"
      Events:
        GenerateImageAPI:
          Type: Api
          Properties:
            Path: /gen-image
            Method: POST

Outputs:
  HelloWorldApi:
    Description: API Gateway endpoint URL for Prod stage for Hello World function
    Value: !Sub "https://${ServerlessRestApi}.execute-api.${AWS::Region}.amazonaws.com/Prod/gen-image"
  HelloWorldFunction:
    Description: Hello World Lambda Function ARN
    Value: !GetAtt HelloWorldFunction.Arn
  HelloWorldFunctionIamRole:
    Description: Implicit IAM Role created for Hello World function
    Value: !GetAtt HelloWorldFunctionRole.Arn
